server:
  http_listen_port: 9080
  log_level: debug

positions:
  filename: /var/positions.yaml

clients:
  - url: http://15.164.91.222:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/springboot/*.log
